In [1]:
# Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

/Users/tanneramman/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
allData = pd.read_csv('/Users/tanneramman/Downloads/CensusWeatherCounties.csv', header = 1)

In [3]:
allData.head()

,Unnamed: 0,County,Estimate!!Total:,Estimate!!Total:!!Utility gas,"Estimate!!Total:!!Bottled, tank, or LP gas",Estimate!!Total:!!Electricity,"Estimate!!Total:!!Fuel oil, kerosene, etc.",Estimate!!Total:!!Coal or coke,Estimate!!Total:!!Wood,Estimate!!Total:!!Solar energy,...,Longitude,tempmax,tempmin,temp,humidity,precipcover,cloudcover,solarradiation,solarenergy,uvindex
0,NaN,Phillips,1689,1041,264,347,2,0,0,0,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
1,NaN,Archuleta,5858,2510,1736,591,0,4,862,55,...,-107.050863,59.490385,32.628846,45.607692,54.287821,6.196667,27.409615,218.167308,17.635256,7.038462
2,NaN,Denver,301501,202325,3435,88795,363,8,333,814,...,-104.880625,65.848077,39.699359,52.000641,46.857692,5.128077,51.629487,244.592308,14.983333,6.282051
3,NaN,Kiowa,638,402,134,67,0,0,15,0,...,-102.756210,71.191026,38.971795,54.469231,51.231410,3.365449,19.105128,207.478205,16.956410,6.910256
4,NaN,Huerfano,3225,1223,1048,413,0,0,493,19,...,-104.959928,61.376923,35.865385,47.028846,47.954487,6.303782,22.929487,261.196795,16.146795,7.288462

In [4]:
allData.columns

Index(['Unnamed: 0', 'County', 'Estimate!!Total:',
       'Estimate!!Total:!!Utility gas',
       'Estimate!!Total:!!Bottled, tank, or LP gas',
       'Estimate!!Total:!!Electricity',
       'Estimate!!Total:!!Fuel oil, kerosene, etc.',
       'Estimate!!Total:!!Coal or coke', 'Estimate!!Total:!!Wood',
       'Estimate!!Total:!!Solar energy', 'Estimate!!Total:!!Other fuel',
       'Estimate!!Total:!!No fuel used', 'State', 'County Number', 'State.1',
       'FIPS', 'County Seat(s)', 'Population (2010)', 'Land Area km2',
       'Land Area mi2', 'Water Area km2', 'Water Area mi2', 'Total Area km2',
       'Total Area mi2', 'Latitude', 'Longitude', 'tempmax', 'tempmin', 'temp',
       'humidity', 'precipcover', 'cloudcover', 'solarradiation',
       'solarenergy', 'uvindex'],
      dtype='object')

In [5]:
improved = allData.drop(columns = 'Unnamed: 0')

In [6]:
improved.head()

,County,Estimate!!Total:,Estimate!!Total:!!Utility gas,"Estimate!!Total:!!Bottled, tank, or LP gas",Estimate!!Total:!!Electricity,"Estimate!!Total:!!Fuel oil, kerosene, etc.",Estimate!!Total:!!Coal or coke,Estimate!!Total:!!Wood,Estimate!!Total:!!Solar energy,Estimate!!Total:!!Other fuel,...,Longitude,tempmax,tempmin,temp,humidity,precipcover,cloudcover,solarradiation,solarenergy,uvindex
0,Phillips,1689,1041,264,347,2,0,0,0,25,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
1,Archuleta,5858,2510,1736,591,0,4,862,55,81,...,-107.050863,59.490385,32.628846,45.607692,54.287821,6.196667,27.409615,218.167308,17.635256,7.038462
2,Denver,301501,202325,3435,88795,363,8,333,814,2826,...,-104.880625,65.848077,39.699359,52.000641,46.857692,5.128077,51.629487,244.592308,14.983333,6.282051
3,Kiowa,638,402,134,67,0,0,15,0,17,...,-102.756210,71.191026,38.971795,54.469231,51.231410,3.365449,19.105128,207.478205,16.956410,6.910256
4,Huerfano,3225,1223,1048,413,0,0,493,19,24,...,-104.959928,61.376923,35.865385,47.028846,47.954487,6.303782,22.929487,261.196795,16.146795,7.288462

In [7]:
allYears = pd.read_csv('/Users/tanneramman/Downloads/countyWeatherAllYears.csv')

In [8]:
allYears

,County,Estimate!!Total,Estimate!!Total!!Utility gas,"Estimate!!Total!!Bottled, tank, or LP gas",Estimate!!Total!!Electricity,"Estimate!!Total!!Fuel oil, kerosene, etc.",Estimate!!Total!!Coal or coke,Estimate!!Total!!Wood,Estimate!!Total!!Solar energy,Estimate!!Total!!Other fuel,...,Longitude,tempmax,tempmin,temp,humidity,precipcover,cloudcover,solarradiation,solarenergy,uvindex
0,Phillips,1696,934,298,409,2,0,9,0,41,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
1,Phillips,1668,982,313,331,2,0,9,0,23,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
2,Phillips,1689,1041,264,347,2,0,0,0,25,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
3,Phillips,1737,1159,264,277,3,0,1,0,26,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
4,Archuleta,5553,2437,1435,675,0,20,852,57,57,...,-107.050863,59.490385,32.628846,45.607692,54.287821,6.196667,27.409615,218.167308,17.635256,7.038462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,Otero,7761,6097,367,905,0,0,324,0,44,...,-103.721260,70.989103,37.642308,53.663462,52.121795,2.858013,9.526923,220.590385,17.692949,7.205128
252,Broomfield,25938,19014,407,6153,0,0,61,43,184,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
253,Broomfield,26721,19413,435,6504,0,0,63,46,196,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
254,Broomfield,27470,20020,459,6577,0,0,44,79,230,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
255,Broomfield,27199,19786,454,6622,0,0,58,75,132,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923

In [9]:
allYears.columns

Index(['County', 'Estimate!!Total', 'Estimate!!Total!!Utility gas',
       'Estimate!!Total!!Bottled, tank, or LP gas',
       'Estimate!!Total!!Electricity',
       'Estimate!!Total!!Fuel oil, kerosene, etc.',
       'Estimate!!Total!!Coal or coke', 'Estimate!!Total!!Wood',
       'Estimate!!Total!!Solar energy', 'Estimate!!Total!!Other fuel',
       'Estimate!!Total!!No fuel used', 'State', 'County Number', 'Year',
       'Census_Population', 'FIPS', 'County Seat(s)', 'Population (2010)',
       'Land Area km2', 'Land Area mi2', 'Water Area km2', 'Water Area mi2',
       'Total Area km2', 'Total Area mi2', 'Latitude', 'Longitude', 'tempmax',
       'tempmin', 'temp', 'humidity', 'precipcover', 'cloudcover',
       'solarradiation', 'solarenergy', 'uvindex'],
      dtype='object')

In [10]:
allYearsEnergy = allYears[['County', 'Estimate!!Total', 'Estimate!!Total!!Utility gas', 
                           'Estimate!!Total!!Bottled, tank, or LP gas', 'Estimate!!Total!!Electricity',
                           'Estimate!!Total!!Fuel oil, kerosene, etc.', 'Estimate!!Total!!Coal or coke',
                           'Estimate!!Total!!Wood', 'Estimate!!Total!!Solar energy', 
                           'Estimate!!Total!!Other fuel', 'Estimate!!Total!!No fuel used']]

In [11]:
allEnergy = allYears[['County', 'Estimate!!Total', 'Estimate!!Total!!Utility gas', 
                           'Estimate!!Total!!Bottled, tank, or LP gas', 'Estimate!!Total!!Electricity',
                           'Estimate!!Total!!Fuel oil, kerosene, etc.', 'Estimate!!Total!!Coal or coke',
                           'Estimate!!Total!!Wood', 'Estimate!!Total!!Solar energy', 
                           'Estimate!!Total!!Other fuel', 'Estimate!!Total!!No fuel used', 'Year']]
allEnergy

,County,Estimate!!Total,Estimate!!Total!!Utility gas,"Estimate!!Total!!Bottled, tank, or LP gas",Estimate!!Total!!Electricity,"Estimate!!Total!!Fuel oil, kerosene, etc.",Estimate!!Total!!Coal or coke,Estimate!!Total!!Wood,Estimate!!Total!!Solar energy,Estimate!!Total!!Other fuel,Estimate!!Total!!No fuel used,Year
0,Phillips,1696,934,298,409,2,0,9,0,41,3,2017
1,Phillips,1668,982,313,331,2,0,9,0,23,8,2018
2,Phillips,1689,1041,264,347,2,0,0,0,25,10,2019
3,Phillips,1737,1159,264,277,3,0,1,0,26,7,2020
4,Archuleta,5553,2437,1435,675,0,20,852,57,57,20,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
251,Otero,7761,6097,367,905,0,0,324,0,44,24,2020
252,Broomfield,25938,19014,407,6153,0,0,61,43,184,76,2017
253,Broomfield,26721,19413,435,6504,0,0,63,46,196,64,2018
254,Broomfield,27470,20020,459,6577,0,0,44,79,230,61,2019
255,Broomfield,27199,19786,454,6622,0,0,58,75,132,72,2020

In [16]:
def linRegress(xValues, yValues):
    global x 
    x = xValues
    global y
    y = yValues
    global slope, intercept, rvalue, pvalue, stderr
    (slope, intercept, rvalue, pvalue, stderr) = linregress(xValues, yValues)
    global regressValues
    regressValues = xValues * slope + intercept
    global lineEq 
    lineEq = f'y = {str(round(slope, 2))}x + {str(round(intercept, 2))}'

counties = pd.unique(allEnergy['County'])
valueList = []
countyDict = {}
rowCounter = -.5
allYearsCopy = allYears.copy()
    
for i in range (len(counties)):
    county = counties[i]
    countyDf = allEnergy.loc[allEnergy['County'] == county]
    withoutCounty = countyDf.drop(columns = ['County'])
    for column in withoutCounty:
        linRegress(withoutCounty['Year'], withoutCounty[column])
        total = (round(slope * 2021, 2) + round(intercept, 2))
        if (total < 0):
            total = 0
        countyDict[column] = total
    rowCounter+=4    
    countyDict['County'] = county
    countyDict['Year'] = 2021
    allYearsCopy.loc[rowCounter] = countyDict
    countyDict.clear()
        
      
allYearsCopy = allYearsCopy.sort_index().reset_index(drop=True)
allYearsCopy

,County,Estimate!!Total,Estimate!!Total!!Utility gas,"Estimate!!Total!!Bottled, tank, or LP gas",Estimate!!Total!!Electricity,"Estimate!!Total!!Fuel oil, kerosene, etc.",Estimate!!Total!!Coal or coke,Estimate!!Total!!Wood,Estimate!!Total!!Solar energy,Estimate!!Total!!Other fuel,...,Longitude,tempmax,tempmin,temp,humidity,precipcover,cloudcover,solarradiation,solarenergy,uvindex
0,Phillips,1696.0,934.0,298.0,409.0,2.0,0.0,9.0,0.0,41.0,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
1,Phillips,1668.0,982.0,313.0,331.0,2.0,0.0,9.0,0.0,23.0,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
2,Phillips,1689.0,1041.0,264.0,347.0,2.0,0.0,0.0,0.0,25.0,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
3,Phillips,1737.0,1159.0,264.0,277.0,3.0,0.0,1.0,0.0,26.0,...,-102.345105,68.353846,39.351282,52.939744,56.822436,2.590833,16.762821,222.436538,14.953846,5.942308
4,Phillips,1733.5,1212.5,247.0,246.0,3.0,0.0,0.0,0.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,Broomfield,25938.0,19014.0,407.0,6153.0,0.0,0.0,61.0,43.0,184.0,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
316,Broomfield,26721.0,19413.0,435.0,6504.0,0.0,0.0,63.0,46.0,196.0,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
317,Broomfield,27470.0,20020.0,459.0,6577.0,0.0,0.0,44.0,79.0,230.0,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
318,Broomfield,27199.0,19786.0,454.0,6622.0,0.0,0.0,58.0,75.0,132.0,...,-105.052125,65.878205,40.276282,52.743590,47.248718,5.181603,24.457051,170.991667,14.496154,6.576923
319,Broomfield,27965.0,20289.0,480.0,6834.0,0.0,0.0,49.5,93.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
allYearsCopy.to_csv("/Users/tanneramman/Downloads/energyDataLinear2021.csv")